name: Build Course Materials

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      
    - name: Set up LaTeX
      uses: xu-cheng/latex-action@v2
      
    - name: Build LaTeX document
      run: |
        cd latex
        pdflatex main.tex
        bibtex main
        makeindex main
        pdflatex main.tex
        pdflatex main.tex
        
